apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-004616-q65ffg92uabb-service
spec:
  selector:
    app: enterprise-system-20260627-004616-q65ffg92uabb
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
